const OPPORTUNITIES = [
  {
    id: "LX",
    name: "Leucoxene",
    grade: "86% TiO₂",
    region: "West Africa",
    masterRef: "VESS-ALLOC-LX-26",
    masterQty: "60,000 MT",
    allocations: [
      { ref: "VESS-ALLOC-LX-27", qty: "5,000 MT" },
      { ref: "VESS-ALLOC-LX-28", qty: "8,000 MT" },
      { ref: "VESS-ALLOC-LX-29", qty: "12,000 MT" },
      { ref: "VESS-ALLOC-LX-30", qty: "3,000 MT" },
      { ref: "VESS-ALLOC-LX-31", qty: "7,000 MT" },
      { ref: "VESS-ALLOC-LX-32", qty: "4,000 MT" },
      { ref: "VESS-ALLOC-LX-33", qty: "6,000 MT" },
      { ref: "VESS-ALLOC-LX-34", qty: "5,000 MT" },
      { ref: "VESS-ALLOC-LX-35", qty: "10,000 MT" },
      { ref: "VESS-ALLOC-LX-36", qty: "60,000 MT" },
    ],
  },
  {
    id: "IL",
    name: "Ilmenite",
    grade: "47% TiO₂",
    region: "West Africa",
    masterRef: "VESS-ALLOC-IL",
    masterQty: "50,000 MT",
    allocations: [
      { ref: "VESS-ALLOC-IL-24", qty: "6,000 MT" },
      { ref: "VESS-ALLOC-IL-25", qty: "4,000 MT" },
      { ref: "VESS-ALLOC-IL-26", qty: "8,000 MT" },
      { ref: "VESS-ALLOC-IL-27", qty: "5,000 MT" },
      { ref: "VESS-ALLOC-IL-28", qty: "7,000 MT" },
      { ref: "VESS-ALLOC-IL-29", qty: "3,000 MT" },
      { ref: "VESS-ALLOC-IL-30", qty: "9,000 MT" },
      { ref: "VESS-ALLOC-IL-31", qty: "8,000 MT" },
      { ref: "VESS-ALLOC-IL-32", qty: "50,000 MT" },
    ],
  },

  {
    id: "CH",
    name: "Chromite",
    grade: "47% Cr₂O₃",
    region: "East Africa",
    masterRef: "VESS-ALLOC-CH",
    masterQty: "5,000 MT",
    allocations: [
      { ref: "VESS-ALLOC-CH-21", qty: "300 MT" },
      { ref: "VESS-ALLOC-CH-22", qty: "500 MT" },
      { ref: "VESS-ALLOC-CH-23", qty: "750 MT" },
      { ref: "VESS-ALLOC-CH-24", qty: "400 MT" },
      { ref: "VESS-ALLOC-CH-25", qty: "600 MT" },
      { ref: "VESS-ALLOC-CH-26", qty: "950 MT" },
      { ref: "VESS-ALLOC-CH-27", qty: "500 MT" },
      { ref: "VESS-ALLOC-CH-28", qty: "1,000 MT" },
      { ref: "VESS-ALLOC-CH-29", qty: "5,000 MT" },
    ],
  },
  {
    id: "CU",
    name: "Copper Sheets",
    grade: "99.99% Cu",
    region: "Central Africa",
    masterRef: "VESS-ALLOC-CU",
    masterQty: "10,000 MT",
    allocations: [
      { ref: "VESS-ALLOC-CU-31", qty: "500 MT" },
      { ref: "VESS-ALLOC-CU-32", qty: "1,000 MT" },
      { ref: "VESS-ALLOC-CU-33", qty: "750 MT" },
      { ref: "VESS-ALLOC-CU-34", qty: "1,250 MT" },
      { ref: "VESS-ALLOC-CU-35", qty: "1,500 MT" },
      { ref: "VESS-ALLOC-CU-36", qty: "2,000 MT" },
      { ref: "VESS-ALLOC-CU-37", qty: "1,000 MT" },
      { ref: "VESS-ALLOC-CU-38", qty: "2,000 MT" },
      { ref: "VESS-ALLOC-CU-39", qty: "10,000 MT" },
    ],
  },
  {
    id: "CZS",
    name: "Copper-Zinc Sulfides",
    grade: "28% Cu / 28% Zn",
    region: "East Africa",
    masterRef: "VESS-ALLOC-CZS",
    masterQty: "40,000 MT",
    allocations: [
      { ref: "VESS-ALLOC-CZS-41", qty: "2,000 MT" },
      { ref: "VESS-ALLOC-CZS-42", qty: "3,000 MT" },
      { ref: "VESS-ALLOC-CZS-43", qty: "5,000 MT" },
      { ref: "VESS-ALLOC-CZS-44", qty: "2,500 MT" },
      { ref: "VESS-ALLOC-CZS-45", qty: "4,500 MT" },
      { ref: "VESS-ALLOC-CZS-46", qty: "6,000 MT" },
      { ref: "VESS-ALLOC-CZS-47", qty: "3,500 MT" },
      { ref: "VESS-ALLOC-CZS-48", qty: "5,500 MT" },
      { ref: "VESS-ALLOC-CZS-49", qty: "3,000 MT" },
      { ref: "VESS-ALLOC-CZS-50", qty: "5,000 MT" },
      { ref: "VESS-ALLOC-CZS-51", qty: "40,000 MT" },
    ],
  },
//   {
//     id: "COL",
//     name: "Coltan",
//     grade: "Tantalum-Niobium Mineral Concentrate",
//     region: "West Africa",
//     masterRef: "VESS-ALLOC-COL",
//     masterQty: "10,000 MT",
//     allocations: [
//       { ref: "VESS-ALLOC-COL-11", qty: "500 MT" },
//       { ref: "VESS-ALLOC-COL-12", qty: "1,500 MT" },
//       { ref: "VESS-ALLOC-COL-13", qty: "2,000 MT" },
//       { ref: "VESS-ALLOC-COL-14", qty: "300 MT" },
//       { ref: "VESS-ALLOC-COL-15", qty: "1,200 MT" },
//       { ref: "VESS-ALLOC-COL-16", qty: "1,000 MT" },
//       { ref: "VESS-ALLOC-COL-17", qty: "2,500 MT" },
//       { ref: "VESS-ALLOC-COL-18", qty: "1,000 MT" },
//       { ref: "VESS-ALLOC-COL-19", qty: "10,000 MT" },
//     ],
//   },
];

export default OPPORTUNITIES;